# Generated by Django 4.2.2 on 2023-06-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerPublicKey', models.TextField()),
                ('sellingAmount', models.BigIntegerField()),
                ('sellingToken', models.TextField()),
                ('buyerPublicKey', models.TextField()),
                ('buyingAmount', models.BigIntegerField()),
                ('buyingToken', models.TextField()),
                ('expiryDate', models.TextField()),
                ('physicalAsset', models.BooleanField()),
            ],
        ),
    ]
