# Generated by Django 4.2.2 on 2023-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
